threshold: 0.6
fit:
  positive:
    源头工厂: 1.0
    工厂直供: 0.9
    生产加工: 0.8
    自有工厂: 1.0
    实力商家: 0.6
    实地认证: 0.7
    可定制: 0.4
    支持OEM: 0.6
    支持ODM: 0.6
  negative:
    贸易: -0.6
    批发: -0.4
    代理: -0.6
trust:
  audited: 0.2
  years_weight: 0.02